# Generated by Django 5.1.6 on 2025-02-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_email_ticketimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='internal_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Внутренний номер'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='error_description',
            field=models.TextField(verbose_name='Описание проблемы'),
        ),
    ]
